[build]
  command = "npm install --prefix backend --include=dev && npm run prisma:generate --prefix backend && npm install --prefix frontend --include=dev && npm run build --prefix frontend"
  publish = "frontend/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["backend/prisma/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
